# Generated by Django 2.0.2 on 2018-06-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='chefe_imediato',
            field=models.ManyToManyField(blank=True, null=True, related_name='_funcionario_chefe_imediato_+', to='controle.Funcionario'),
        ),
    ]
