# Generated by Django 2.0.2 on 2018-06-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_funcionario_chefe_imediato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='chefe_imediato',
            field=models.ManyToManyField(blank=True, related_name='_funcionario_chefe_imediato_+', to='controle.Funcionario'),
        ),
    ]
